# Generated by Django 4.2 on 2024-11-01 10:00

import bot.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='course_duration')),
                ('course_duration_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='course_duration')),
                ('course_duration_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='course_duration')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[bot.validators.phone_number_validator], verbose_name='phone number')),
                ('user_lang', models.CharField(blank=True, max_length=10, null=True, verbose_name='user language')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram id')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram username')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.course')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
