# Generated by Django 4.2 on 2024-10-31 10:18

import bot.models
import bot.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='course_duration')),
                ('course_duration_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='course_duration')),
                ('course_duration_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='course_duration')),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[bot.validators.phone_number_validator], verbose_name='phone number')),
                ('user_lang', models.CharField(blank=True, max_length=10, null=True, verbose_name='user language')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram id')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram username')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.course')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', bot.models.CustomUserManager()),
            ],
        ),
    ]
